/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedModeracaoRouteImport } from './routes/_authenticated/moderacao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConteudoRouteImport } from './routes/_authenticated/conteudo'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedModeracaoRoute = AuthenticatedModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConteudoRoute = AuthenticatedConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/conteudo': typeof AuthenticatedConteudoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/moderacao': typeof AuthenticatedModeracaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/admin'
    | '/conteudo'
    | '/dashboard'
    | '/moderacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/admin'
    | '/conteudo'
    | '/dashboard'
    | '/moderacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/conteudo'
    | '/_authenticated/dashboard'
    | '/_authenticated/moderacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/moderacao': {
      id: '/_authenticated/moderacao'
      path: '/moderacao'
      fullPath: '/moderacao'
      preLoaderRoute: typeof AuthenticatedModeracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudo': {
      id: '/_authenticated/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof AuthenticatedConteudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConteudoRoute: typeof AuthenticatedConteudoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedModeracaoRoute: typeof AuthenticatedModeracaoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConteudoRoute: AuthenticatedConteudoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedModeracaoRoute: AuthenticatedModeracaoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
